version: "3.9"
services:
  tomcat:
    image: tomcat:9.0.45-jdk11-adoptopenjdk-openj9
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - task-net
    volumes:
      - ./task-generator-ws/target/:/usr/local/tomcat/webapps
    environment:
      PERSISTENCE_UNIT: docker
  db:
    image: mysql:8.0.23
    restart: always
    networks:
      - task-net
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: javausr
      MYSQL_PASSWORD: javapw
      MYSQL_DATABASE: taskgen
networks:
  task-net:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 10.10.23.0/24
          gateway: 10.10.23.1